# Generated by Django 5.2.1 on 2026-09-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('property_type', models.CharField(choices=[('manor', 'Manor'), ('estate', 'Estate'), ('townhouse', 'Townhouse'), ('cottage', 'Cottage'), ('land', 'Land')], default='estate', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(help_text="City / region, e.g. 'Braevale, Scotland'", max_length=200)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('area_sqft', models.PositiveIntegerField(default=0)),
                ('year_established', models.PositiveIntegerField(blank=True, help_text='Year the property was originally built', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='properties/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='listings.property')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
