# Generated by Django 5.2.1 on 2026-09-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('under_offer', 'Under Offer'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
